theme: jekyll-theme-minimal
title: Ciao...
author: Axel
description: Here is my stuff.
include:
  - "_img"

social-network-links:
  email: "someone@example.com"
  github: daattali
  twitter: daattali
  linkedin: DeanAttali
  youtube: c/daattali
