theme: jekyll-theme-minimal
title: Ciao...
author: Axel
description: Here is my stuff. <br> Name: Axel <br> Born: 1997 <br> Birthplace: Italy
rss-description: This website is a virtual proof that I'm awesome
logo: /assets/guts-leaves.png
